-- Melipilla
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Darío", "Melo", "123456780", "1992-03-15", "Jocker", null, 22, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Cristóbal", "Vergara", "234567890", "1995-07-22", "El Patrón", null, 19, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Erick", "Millalén", "345678901", "1998-12-05", "Milla", null, 5, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Matías", "Rodríguez", "456789012", "1991-04-19", "Mati", null, 6, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Cristian", "Magaña", "567890123", "1996-09-11", "Maga", null, 17, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Albano", "Becica", "678901234", "1999-02-28", "El Abuelo", null, 29, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Valentin", "Demateis", "789012345", "1987-08-03", null, null, 30, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Josue", "Ovalle", "890123456", "1997-11-27", "Cotto", null, 10, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Bryan", "Taiva", "901234567", "1994-06-16", null, null, 14, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Franco", "Ortega", "012345678", "1990-01-09", null, null, 11, true, true, 4)
INSERT INTO t_player(firstname, lastname, run, birth_date, nickname, image_url, squad_number, is_active, is_enabled, team_id) VALUES ("Luis", "Vargas", "135792468", "2000-05-20",  "Tanque", null, 9, true, true, 4)
