-- Equipos Primera División 2025
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Audax Italiano", "AUX", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Cobresal", "CBS", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Colo Colo", "CC", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Coquimbo Unido", "COQ", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Iquique", "DIQ", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes La Serena", "LSR", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Limache", "LIM", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Everton", "EVE", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Huachipato", "HUA", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Nublense", "NUB", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("O'Higgins", "OHI", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Palestino", "PAL", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Unión Española", "UE", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Unión La Calera", "ULC", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Universidad Católica", "UC", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Universidad de Chile", "UCH", null, true, true, 1)

-- Equipos Primera B 2025
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Cobreloa", "COB", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Curicó Unido", "CUR", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Antofagasta", "ANT", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Concepción", "CCP", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Copiapó", "COP", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Recoleta", "REC", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Santa Cruz", "DSC", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Temuco", "TEM", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Magallanes", "MAG", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Rangers", "RAN", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("San Luis de Quillota", "SLU", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("San Marcos de Arica", "SMA", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Santiago Morning", "SMO", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Santiago Wanderers", "SW", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Unión San Felipe", "USF", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Universidad de Concepción", "UDC", null, true, true, 1)

-- Equipos Segunda 2025
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Brujas de Salamanca", "BRS", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Concón National", "CCN", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Linares", "LIN", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Melipilla", "MEL", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Puerto Montt", "DPM", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Rengo", "REN", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("General Velásquez", "GVZ", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Provincial Osorno", "OSO", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Provincial Ovalle", "OVA", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Real San Joaquín", "RSJ", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("San Antonio Unido", "SAU", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Santiago City", "SCT", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Trasandino", "TRA", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("AC Barnechea", "BAR", null, true, true, 1)