INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Concon National", "CCN", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Concepción", "CCP", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Linares", "LIN", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Melipilla", "MEL", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Puerto Montt", "DPM", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Deportes Rengo", "REN", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Fernández Vial", "AFV", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("General Velázquez", "GVZ", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Lautaro de Buin", "LAU", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Provincial Osorno", "OSO", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Provincial Ovalle", "OVA", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Real San Joaquín", "RSJ", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("San Antonio Unido", "SAU", null, true, true, 1)
INSERT INTO t_team (name, team_code, image_url, is_active, is_enabled, user_id) VALUES ("Trasandino", "TRA", null, true, true, 1)